<h2> Using NumPy </h2>

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np

Numpy has many built-in functions and capabilities.

<h2> Numpy Arrays </h2>

Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d(but matrix can still have only one row or one column).

<h2>Creating NumPy Arrays</h2>

<h4> From a Python List </h4>

we can create an array by directly converting a list or list of lists:

In [2]:
my_list = [1,2,3]

In [3]:
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

<h2> Built-in Methods </h2>
There are lots of built-in ways to generate Arrays

<h4>arange</h4>
Return evenly spaced values within a given interval.

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

<h4> zeros and ones </h4>
Generate arrays of zeros and ones

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(3)

array([1., 1., 1.])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

<h4> linspace </h4>
Return evenly spaced numbers over a specified interval

In [15]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [16]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

<h3> eye </h3>

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

<h2> Random </h2>
Numpy also has lots of ways to create random number arrays:
<h3> rand </h3>
Create an array of the given shape and populate it with random samples from a uniform distribution over [0,1).

In [18]:
np.random.rand(2)

array([0.24500885, 0.53042182])

In [19]:
np.random.rand(5,5)

array([[0.10196703, 0.34608483, 0.15890899, 0.38796486, 0.00334899],
       [0.60589159, 0.67770542, 0.07653546, 0.23740457, 0.62386742],
       [0.09192304, 0.6788592 , 0.70898004, 0.46186788, 0.40249594],
       [0.12640235, 0.84645227, 0.46762025, 0.30501575, 0.13921094],
       [0.71597876, 0.49102753, 0.09060121, 0.85355252, 0.6925725 ]])

<h3> randn </h3>
Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [20]:
np.random.randn(2)

array([-1.25620661,  1.06392469])

In [21]:
np.random.randn(5,5)

array([[ 1.11300742e+00, -8.06208145e-01,  2.28261156e+00,
         2.06904353e+00, -7.85955561e-01],
       [-6.66535998e-01,  1.29877711e-01, -4.10620528e-01,
         1.42477645e+00, -2.07620603e-03],
       [ 2.60788806e-01,  6.90581719e-01,  1.67145370e-01,
         1.28378564e+00, -6.45974819e-01],
       [ 2.69492632e-01, -2.34522558e+00, -3.50093926e-02,
         8.06580027e-01,  7.81604087e-01],
       [ 1.27891439e+00, -1.43999298e+00, -4.02822471e-01,
        -4.38530708e-02, -1.19628942e+00]])

<h3>randint</h3>

In [22]:
np.random.randint(1,100)

71

In [23]:
np.random.randint(1,100,10)

array([81, 78, 31, 94,  3, 16, 77, 29, 11, 74])

<h2> Array Attributes and Methods </h2>
Let's discuss some useful attributes and methods or an array:

In [24]:
arr = np.arange(25)

In [25]:
ranarr = np.random.randint(0,50,10)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr

array([17,  6, 17, 40, 27, 17,  0, 16, 41, 42])

<h2> Reshape </h2>
Returns an array containing the same data with a new shape.

In [28]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

<h3> max, min, argmax, argmin </h3>
These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [29]:
ranarr

array([17,  6, 17, 40, 27, 17,  0, 16, 41, 42])

In [30]:
ranarr.max()

42

In [31]:
ranarr.min()

0

In [32]:
ranarr.argmax()

9

In [33]:
ranarr.argmin()

6

<h2> Shape </h2>
Shape is an attribute that arrays have(not a method):

In [34]:
# Vector
arr.shape

(25,)

In [ ]:
#