<h2> NumPy Indexing and Selection </h2>
Select elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
#Creating sample array
arr = np.arange(0,11)

In [3]:
#show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

<h3> Bracket Indexing and Selection </h3>
The simplest way to pick one or more elements of an array looks very similar to python lists:

In [4]:
#Get a value at an index
arr[8]

8

In [5]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [6]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

<h3> Broadcasting </h3>
Numpy arrays differ from a normal Python list because of their ability to broadcat:

In [7]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

In [8]:
#show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
# Reset array, we'll see why I had to reset in a moment
arr = np.arange(0,11)

In [10]:
#show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
#Important notes on Slices
slice_of_arr = arr[0:6]

In [12]:
#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [14]:
#Change Slice
slice_of_arr[:] = 99

In [15]:
#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [16]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [17]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

In [18]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

<h3> Indexing a 2D array (matrices) </h3>
The general format is arr_2d[row][col] or arr_2d[row,col]. I recommend usually using the comma notation for clarity.

In [19]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [20]:
#show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [21]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [22]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [23]:
# Getting individual element value
arr_2d[2,1]

40

In [24]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [25]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [26]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

<h3> Fancy Indexing </h3>
Fancy indexing allows you to select entire rows or columns out of order, to show this, let's quickly build out a numpy array:

In [28]:
#Set up matrix
arr2d = np.zeros((10,10))

In [29]:
#length of array
arr_length = arr2d.shape[1]

In [31]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i

arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [32]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [33]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [34]:
arr_length

10

<h3> Selection </h3>
Let's briefly go over how to use brackets for selection based off of comparison operators.

In [35]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [37]:
bool_arr = arr > 4

In [38]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [39]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [40]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
x = 2
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])